drop table Product if exists;

create table Product (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT not null DEFAULT 0,
    productCode varchar(255),
    name varchar(255),
    productType varchar(255),
    primary key (id)
);